### ISSUE TITLE
Ternary Operator

### ISSUE THREAD

**Issue by richpeck** [SimonSomlai/truetech-v3#1]
https://github.com/SimonSomlai/truetech-v3/blob/master/app/uploaders/testimonial_picture_uploader.rb#L6

Could be:

    storage (Rails.env.production? ? :fog : :file)

--

https://en.wikipedia.org/wiki/Ternary_operation
http://stackoverflow.com/questions/4252936/how-do-i-use-the-conditional-operator-in-ruby

**Comment by SimonSomlai** [comment]
Hey Rich, thanks for the tips man :) 

They are appreciated! I've included the changes in the app. 

You're the person who built this: http://www.theultimatecommonplacesystem.com/ for Ludvig right?

**Comment by richpeck** [comment]
No problem! I helped with the site and artwork, yes
